name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Frontend Steps
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend/auto-job-applier

      - name: Run frontend tests
        run: npm run test:unit
        working-directory: ./frontend/auto-job-applier

      # Backend Steps
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install backend dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt

      - name: Run backend tests
        run: |
          source venv/bin/activate
          pytest backend/tests
