name: CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - "frontend/**"
      - "backend/**"
  pull_request:
    branches:
      - main
      - master
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'frontend')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend/auto-job-applier

      - name: Run frontend tests
        run: npm run test:unit
        working-directory: ./frontend/auto-job-applier

  backend-test:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'backend')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9.]+')
          CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-with-downloads.json" | jq -r --arg CHROME_VERSION "$CHROME_VERSION" '.chrome.versions[$CHROME_VERSION] | .chromedriver')
          wget -N "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chown root:root /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Install backend dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install .
        working-directory: ./backend

      - name: Verify tests directory exists
        run: ls -la tests
        working-directory: ./backend

      - name: Print environment variables
        run: printenv

      - name: Run backend tests
        run: |
          source venv/bin/activate
          pytest tests
        working-directory: ./backend
